### ISSUE TITLE
Use with MKR1310 - no radio signal

### ISSUE THREAD

**Issue by disk91** [hardwario/lora-modem-abz#108]
Hello, 

I've been successfully able to flash the last release of the firmware on the Arduino MKR1310 board. The AT commands works perfectly and I can setup the devEUI as expected.

But When trying to Join, It failed (no response from LNS), The LNS did not received the Join Requets.
My investigations conducted to no radio transmission during the JOIN phase ( flat spectrum analyzer on 867-869) 

Any idea ?

**Comment by janakj** [comment]
Have you switched the modem to OTAA mode with `AT+MODE=1`? It's in ABP mode by default after factory reset.

**Comment by disk91** [comment]
Yes I did it.

I did a test with a MKR1300 and I've got a radio signal received by LNS.
But with my MKR1310 no radio signal. 

Do you know if anyone, on last release, had a success in using it on a MKR1310 on EU868 ? (in that case it could be a board failure ... I'll double check with the standard firmware also to see if there is a difference).

**Comment by janakj** [comment]
Glad to hear the firmware worked for you on a MKR1300! You'll probably the first to make it work on a MKRWAN board.

Regarding MKRWAN1300, I am looking at the schematic and I just noticed that this board has the VDD_TCXO pin (pin 48) wired differently. On MKRWAN1300 boards this pin was connected to the 3.3V rail. On MKRWAN13100 boards it seems to be connected to PB6/LPTIM1_ETR, presumably to allow the firmware enable or disable the internal TXCO IC. I am not sure what reason for this change is, perhaps power optimization?

Since I am not touching the configuration of the PB6/LPTIM1_ETR in the firmware, I wonder if the modem is not transmitting because the TXCO IC is powered off. All my modems (which are not MKRWAN based) have VDD_TCXO hardwired to 3.3V as well.

**Comment by disk91** [comment]
Using PA12 is standard even if it's a problem when you want to use the USB port. 
I confirm your fix is resolving the transmission issue : radio signal seen on Spectrum analyzer and response from the AT+JOIN
```
23:03:04.407 -> +OK
23:03:04.407 -> 
23:03:12.165 -> +EVENT=1,1
```

**Comment by disk91** [comment]
Thank you so much for the help.
I'll package a FW upgrade sketch for Arduino MKR1310 (your firmware is the way to select you own devEUI what Arduino do not support). Let me know if you plan a new release with this patch, so I'll update with it.
Paul

**Comment by janakj** [comment]
Thanks for confirming. Yes, I will include this patch in the next release. But before I can do that, I will have to update my release scripts to generate two binary firmware variants. One for MKRWAN1310 with TCXO control on PB6 and debugging on USART2, and one for everything else.

**Comment by disk91** [comment]
Thank you

**Comment by disk91** [comment]
If anyone needs to deploy this FW on MKR1310, here is a fw loader project including the version above
https://github.com/disk91/mkr1310_openLoRaModem_fw_update
